---

services:
  frontend:
    build: ./frontend
    container_name: frontend_01
    command: run 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      web:
        condition: service_healthy
  web:
    build: ./web
    container_name: django_01
    volumes:
      - .:/web_django
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/health/ || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
  db:
    image: postgres:16-alpine
    container_name: postgres_01
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pwd123
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./db_django:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d django_db"]
      interval: 60s
      timeout: 10s
      retries: 3